services:
  app:
    build: .
    volumes:
      - .:/app
    command: python --version

  train:
    build: .
    volumes:
      - .:/app
    command: python train.py --timesteps 200000 --reward_type shaped --save_path models/ppo_shaped.zip

  train_baseline:
    build: .
    volumes:
      - .:/app
    command: python train.py --timesteps 200000 --reward_type baseline --save_path models/ppo_baseline.zip

  evaluate:
    build: .
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
      - SDL_VIDEODRIVER=dummy
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/app
    command: xvfb-run -a python evaluate.py --model_path models/ppo_shaped.zip --gif_path media/agent_final.gif

  plot:
    build: .
    volumes:
      - .:/app
    command: python plot.py
